version: '2'

services:

    db:
        image: mysql:5.7
        volumes:
            - "./.data/db:/var/lib/mysql"
            - "../:/project"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    php:
        build:
            context: php7-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/app/logs

    nginx:
        build: nginx
        ports:
            - 80:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx

    es:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
        ports:
            - 9200:9200
        volumes:
            - "./.data/es:/usr/share/elasticsearch/data"
        environment:
            - xpack.security.enabled=false
        
    #elk:
    #    image: willdurand/elk
    #    ports:
    #        - 81:80
    #    volumes:
    #        - ./elk/logstash:/etc/logstash
    #        - ./elk/logstash/patterns:/opt/logstash/patterns
    #    volumes_from:
    #        - php
    #        - nginx
  
